# Generated by Django 4.1.7 on 2023-04-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='messsage',
            new_name='message',
        ),
    ]
